# Lời Tựa {-}

Kinh Pháp Cú là một bộ sưu tập Ðá Quý và hẳn là kim chỉ nam cho mỗi phật tử. Nội dung bản kinh nên được đọc đi, đọc lại, nghiên cứu, quán triệt và, trên hết, là phải áp dụng hằng ngày.

Những câu danh ngôn vàng ngọc được thể hiện trong bản Kinh này đã minh chứng hùng hồn những lời dạy đạo đức và triết học của Ðức Phật.

Ðộc giả sẽ nhận thấy sự so sánh giản dị được Ðức Phật ứng dụng trong Kinh Pháp Cú mà ngay cả một em nhỏ cũng có thể hiểu được. Ví dụ như so sánh bánh xe bò, bóng người, căn nhà lợp vụng, ngôi làng đang ngủ, hồ nước sâu thẳm v.v... Sự vĩ đại của Ðức Phật là ở chỗ Ngài trình bày những sự thật uyên thâm bằng những ngôn từ giản dị.

Trong Kinh Pháp Cú có nhiều trường hợp cho thấy Ðức Phật không những thuyết giảng cho giới trí thức và hàng trưởng lão, mà còn giáo dục trẻ em bằng ngôn ngữ của riêng chúng.

Trong khi chuẩn bị bản dịch này, tôi đã tham khảo tất cả những bản dịch có giá trị, và tôi phải thừa nhận rằng chúng vô cùng ích lợi cho tôi.

<div style="text-align: right">
NARADA MAHATHERA  
Tháng 7 ngày 14 năm 1962  
Tu viện Vajirarama, Colombo, Sri Lanka
</div>


## Lời người biên tập {-}

Cuốn sách này là bộ sưu tập Kinh Pháp Cú bằng tiếng Pāḷi, cùng các bản dịch từ Pāḷi sang tiếng Việt của Hòa thượng Thích Minh Châu, Tỳ-kheo Đức Hiền, dịch giả Tịnh Minh, bản thơ hóa của Hòa thượng Giới Đức, bản dịch từ Pāḷi sang tiếng Anh của Ngài Narada Mahathera, bản dịch Anh - Việt của dịch giả Phạm Kim Khánh, cùng tranh minh họa của họa sĩ P. Wickramanayaka.  

Các nguồn tham khảo:  

- [Dhammapada (Illustrated)](https://www.wisdomlib.org/buddhism/book/dhammapada-illustrated)
- [The Dhammapada, Pāḷi text & translation with stories in brief & notes](https://archive.org/details/DhammapadaWithNotes)
- [Kinh Pháp Cú, phân tích từ ngữ Pāḷi](./books/kinh_phap_cu_phan_tich_tu_ngu_Pali.pdf)
- [Thi kệ Pháp Cú (Pāḷi - Anh - Việt)](https://www.budsas.org/uni/u-kinh-phapcu-ev/pctm-00.htm)
- [Kinh Pháp Cú - Nguyên tác Pāḷi, bản dịch Việt ngữ cùng với câu chuyện dẫn tích tóm tắt và chú thích](https://www.budsas.org/uni/u-kinh-phapcu-ev/pkk-00.htm)
- [Suttacentral](https://suttacentral.net/dhp?view=normal&lang=en)


Trong quá trình biên tập không thể tránh khỏi những sai sót. Trong trường hợp quý độc giả phát hiện lỗi sai nào, xin gửi thư cho chúng tôi qua địa chỉ [tonkinhphap@gmail.com](mailto:tonkinhphap@gmail.com?subject=[Kinh Pháp Cú]) với tiêu đề bắt đầu bằng: "*[Kinh Pháp Cú]*". Xin chân thành cảm ơn.