# Mục lục {- #muc-luc}

[**Phẩm Song Đối**](./pham-song-doi.html)

- [Kệ số 1: Làm ác gặp dữ](./lam-ac-gap-du.html)  
- [Kệ số 2: Hành thiện gặp lành](./hanh-thien-gap-lanh.html)  
- [Kệ số 3, 4: Trả thù báo oán không dẫn đến an tịnh](./tra-thu-bao-oan.html)  
- [Kệ số 5: Tình thương chinh phục sân hận](./tinh-thuong-chinh-phuc-san-han.html)  
- [Kệ số 6: Tư tưởng chân chính chấm dứt bất hòa](./tu-tuong-chan-chinh-cham-dut-bat-hoa.html)  
- [Kệ số 7, 8: Người yếu sa ngã trước cám dỗ](./nguoi-yeu-sa-nga-truoc-cam-do.html)  
- [Kệ số 9, 10: Xứng áo cà sa](./xung-ao-ca-sa.html)  
- [Kệ số 11, 12: Tri kiến chân chính](./tri-kien-chan-chinh.html)  
- [Kệ số 13, 14: Tham dục đâm thủng tâm người không trau giồi](./tham-duc.html)  
- [Kệ số 15: Người làm ác chịu khổ](./nguoi-lam-ac-chiu-kho.html)  
- [Kệ số 16: Người hành thiện có hạnh phúc](./nguoi-hanh-thien-hanh-phuc.html)  
- [Kệ số 17: Người làm ác than van](./lam-ac-than-van.html)  
- [Kệ số 18: Người sống chân chính được hạnh phúc](./song-chan-chinh-duoc-hanh-phuc.html)  
- [Kệ số 19, 20: Học mà không hành thì vô bổ](./hoc-ma-khong-hanh-thi-vo-bo.html)  

[**Phẩm Không Xao Lãng**](./pham-khong-xao-lang.html)

- [Kệ số 21 - 23: Phóng dật như chết rồi](./phong-dat-nhu-chet-roi.html)  
- [Kệ số 24: Người tinh tấn được sung túc](./tinh-tan-duoc-sung-tuc.html)  
- [Kệ số 25: Bậc thiện trí tạo thiên đàng cho chính mình](./bac-thien-tri-tao-thien-dang-cho-minh.html)  
- [Kệ số 26, 27: Hãy chú niệm, không nên phóng dật](./chu-niem-khong-phong-dat.html)  
- [Kệ số 28: Dùng tâm niệm khắc phục phóng dật](./dung-tam-niem-khac-phuc-phong-dat.html)  
- [Kệ số 29: Kiên trì cố gắng](./kien-tri-co-gang.html)  
- [Kệ số 30: Chuyên cần dẫn đến quyền tối thượng](./chuyen-can-dan-den-quyen-toi-thuong.html)  
- [Kệ số 31: Người chuyên cần vững tiến](./nguoi-chuyen-can-vung-tien.html)  
- [Kệ số 32: Người chuyên cần đối diện Niết-bàn](./nguoi-chuyen-can-doi-dien-niet-ban.html)  

[**Phẩm Tâm**](./pham-tam.html)

- [Kệ số 33, 34: Hãy giữ vững cái tâm chao động của ta](./hay-giu-vung-cai-tam-chao-dong-cua-ta.html)  
- [Kệ số 35: Hãy kiểm soát tâm](./hay-kiem-soat-tam.html)  
- [Kệ số 36: Hãy canh chừng tư tưởng](./hay-canh-chung-tu-tuong.html)  
- [Kệ số 37: Người đã kiểm soát tâm sống tự do](./nguoi-da-kiem-soat-tam-song-tu-do.html)  
- [Kệ số 38, 39: Người giác tỉnh không sợ sệt](./nguoi-giac-tinh-khong-so-set.html)  
- [Kệ số 40, 41: Hãy kiên cố tâm và không nên luyến ái](./hay-kien-co-tam-khong-nen-luyen-ai.html)  
- [Kệ số 42: Tâm bất thiện là kẻ thù tệ hại nhất](./tam-bat-thien-la-ke-thu-te-nhat.html)  
- [Kệ số 43: Tâm hướng thiện như cha mẹ](./tam-huong-thien-nhu-cha-me.html)  

[**Phẩm Bông Hoa**](./pham-bong-hoa.html)

- [Kệ số 44, 45: Người cao thượng chinh phục tự ngã](./nguoi-cao-thuong-chinh-phuc-tu-nga.html)  
- [Kệ số 46: Thể xác này tựa hồ một ảo ảnh](./the-xac-nay-tua-ho-mot-ao-anh.html)  
- [Kệ số 47: Cái chết cuốn người không giác tỉnh sống trong dục lạc](./cai-chet-cuon-nguoi-khong-giac-tinh-song-trong-duc-lac.html)  
- [Kệ số 48: Người tham dục chết với dục vọng bất thỏa mãn](./nguoi-tham-duc-chet-voi-duc-vong-bat-thoa-man.html)  
- [Kệ số 49: Bậc thánh tăng không gây tổn hại cho bất cứ ai](./bac-thanh-tang-khong-gay-ton-hai-cho-bat-cu-ai.html)  
- [Kệ số 50: Không tìm lỗi của kẻ khác mà tìm ở chính mình](./khong-tim-loi-ke-khac-ma-tim-o-chinh-minh.html)  
- [Kệ số 51, 52: Thực hành tốt hơn lời giáo huấn suông](./thuc-hanh-tot-hon-loi-giao-huan-suong.html)  
- [Kệ số 53: Hãy tạo nhiều phước báu](./hay-tao-nhieu-phuoc-bau.html)  
- [Kệ số 54, 55: Hương thơm của giới đức bay khắp nơi](./huong-thom-cua-gioi-duc-bay-khap-noi.html)  
- [Kệ số 56: Hương thơm của đức hạnh cao quý nhất](./huong-thom-cua-duc-hanh-cao-quy-nhat.html)  
- [Kệ số 57: Không thể theo dấu thức tái sanh của một vị A-La-Hán](./khong-the-theo-dau-thuc-tai-sanh-cua-mot-vi-a-la-han.html)  
- [Kệ số 58, 59: Người thấp hèn cũng có điểm cao thượng](./nguoi-thap-hen-cung-co-diem-cao-thuong.html)  


[**Phẩm Kẻ Ngu**]('/pham-ke-ngu.html)

- [Kệ số 60: Luân hồi xa xôi với người không biết giáo pháp](./luan-hoi-xa-xoi-voi-nguoi-khong-biet-giao-phap.html)  
- [Kệ số 61: Tránh kết hợp với người cuồng dại](./tranh-ket-hop-voi-nguoi-cuong-dai.html)  
- [Kệ số 62: Chính ta không phải là của ta](./chinh-ta-khong-phai-la-cua-ta.html)  
- [Kệ số 63: Biết nhận thức sự cuồng dại của mình là người trí](./biet-nhan-thuc-su-cuong-dai-cua-minh-la-nguoi-tri.html)  
- [Kệ số 64: Người cuồng dại không thể nhận chân giá trị của giáo pháp](./nguoi-cuong-dai-khong-the-nhan-chan-gia-tri-cua-giao-phap.html)  
- [Kệ số 65: Bậc thiện trí nhận chân giá trị của giáo pháp](./bac-thien-tri-nhan-chan-gia-tri-cua-giao-phap.html)  
- [Kệ số 66: Quả của hành động bất thiện thật là đắng](./qua-cua-hanh-dong-bat-thien-la-dang.html)  
- [Kệ số 67: Hành động là bất thiện nếu đem lại hối hận](./hanh-dong-la-bat-thien-neu-dem-lai-hoi-han.html)  
- [Kệ số 68: Hành động là thiện nếu không đem lại hối hận](./hanh-dong-la-thien-neu-khong-dem-lai-hoi-han.html)  
- [Kệ số 69: Người hành ác đi đến phiền não](./nguoi-hanh-ac-di-den-phien-nao.html)  
- [Kệ số 70: Chứng ngộ thập phần cao thượng tuyệt cốc suông](./chung-ngo-thap-phan-cao-thuong-tuyet-coc-suong.html)  
- [Kệ số 71: Hành động bất thiện sẽ trổ quả đúng lúc](./hanh-dong-bat-thien-se-tro-qua-dung-luc.html)  
- [Kệ số 72: Với người cuồng dại, tri thức và danh vọng có khuynh hướng làm sụp đổ họ](./voi-nguoi-cuong-dai-tri-thuc-va-danh-vong-co-khuynh-huong-lam-sup-do-ho.html)  
- [Kệ số 73, 74: Người si mê tìm danh vọng bất chánh](./nguoi-si-me-tim-danh-vong-bat-chanh.html)  
- [Kệ số 75: Con đường Niết-bàn khác con đường danh lợi](./con-duong-niet-ban-khac-con-duong-danh-loi.html)  

[**Phẩm Người Trí**](./pham-nguoi-tri.html)

- [Kệ số 76: Hãy kết hợp với người thiện trí hết lòng khuyến thiện ta](./hay-ket-hop-voi-nguoi-tri-het-long-khuyen-thien-ta.html)  
- [Kệ số 77: Người tốt hoan hỉ với lời khuyên dạy](./nguoi-tot-hoan-hi-noi-loi-khuyen-day.html)  
- [Kệ số 78: Hãy kết hợp với bạn lành](./hay-ket-hop-voi-ban-lanh.html)  
- [Kệ số 79: Người thấm nhuần giáo pháp sống hạnh phúc](./nguoi-tham-nhuan-giao-phap-song-hanh-phuc.html)  
- [Kệ số 80: Bậc thiện trí tự kiểm soát lấy mình](./bac-thien-tri-tu-kiem-soat-lay-minh.html)  
- [Kệ số 81: Người thiện trí không xao động trước khen chê](./nguoi-thien-tri-khong-xao-dong-truoc-khen-che.html)  
- [Kệ số 82: Người trí được an tịnh](./nguoi-tri-duoc-an-tinh.html)  
- [Kệ số 83: Người thiện trí không bồng bột cũng không nản chí](./nguoi-thien-tri-khong-bong-bot-cung-khong-nan-chi.html)  
- [Kệ số 84: Không nên tìm thành công bằng những phương tiện bất chánh](./khong-nen-tim-thanh-cong-bang-nhung-phuong-tien-bat-chanh.html)  
- [Kệ số 85, 86: Người thực hành giáo pháp vượt qua bên kia](./nguoi-thuc-hanh-giao-phap-vuot-qua-ben-kia.html)  
- [Kệ số 87 - 89: Người không luyến ái sống an tịnh](./nguoi-khong-luyen-ai-song-an-tinh.html)  

[**Phẩm A-La-Hán**](./pham-a-la-han.html)

- [Kệ số 90: Bậc thoát tục không còn đau khổ](./bac-thoat-tuc-khong-con-dau-kho.html)  
- [Kệ số 91: Chư vị A-La-Hán không còn luyến ái](./chu-vi-a-la-han-khong-con-luyen-ai.html)  
- [Kệ số 92: Không nên luyến ái vật thực](./khong-nen-luyen-ai-vat-thuc.html)  
- [Kệ số 93: Người không ô nhiễm sống tự do](./nguoi-khong-o-nhiem-song-tu-do.html)  
- [Kệ số 94: Người biết tự chế được tất cả quý mến](./nguoi-biet-tu-che-duoc-tat-ca-quy-men.html)  
- [Kệ số 95: Như đất, chư vị A-La-Hán không chao động](./nhu-dat-chu-vi-a-la-han-khong-chao-dong.html)  
- [Kệ số 96: Người trầm tĩnh sống an tịnh](./nguoi-tram-tinh-song-an-tinh.html)  
- [Kệ số 97: Người không nhẹ dạ là cao quý](./nguoi-khong-nhe-da-la-cao-quy.html)  
- [Kệ số 98: Tịnh lạc thay, nơi nào có A-La-Hán trú ngụ](./tinh-lac-thay-noi-nao-co-a-la-han-tru-ngu.html)  
- [Kệ số 99: Người không dục vọng thỏa thích trong rừng sâu](./nguoi-khong-duc-vong-thoa-thich-trong-rung-sau.html) 

[**Phẩm Một Ngàn**](./pham-mot-ngan.html)

- [Kệ số 100: Một lời hữu ích hơn hằng ngàn tiếng nói vô dụng](./mot-loi-huu-ich-hon-hang-ngan-tieng-noi-vo-dung.html)  
- [Kệ số 101: Một câu hữu ích hơn ngàn câu vô dụng](./mot-cau-huu-ich-hon-ngan-cau-vo-dung.html)  
- [Kệ số 102, 103: Một lời giáo pháp hơn trăm câu vô dụng, tự khắc phục mình là chinh phục cao thượng](./mot-loi-giao-phap-hon-tram-cau-vo-dung.html)  
- [Kệ số 104, 105: Thắng mình hơn thắng người](./thang-minh-hon-thang-nguoi.html)  
- [Kệ số 106: Tôn kính bậc Ứng Cúng quý hơn sùng bái người không xứng](./ton-kinh-bac-ung-cung.html)  
- [Kệ số 107: Tế thần lửa trong một thế kỷ không bằng tôn kính bậc hoàn toàn trong sạch trong giây lát](./ton-kinh-bac-hoan-toan-trong-sach-hon-te-than-lua.html)  
- [Kệ số 108: Tôn kính bậc hoàn toàn trong sạch quý hơn giết thú tế thần](./ton-kinh-bac-hoan-toan-trong-sach-quy-hon-giet-thu-te-than.html)  
- [Kệ số 109: Phước báu tôn tính bậc đáng kính](./phuoc-bau-ton-kinh-bac-dang-kinh.html)  
- [Kệ số 110: Sống ngắn ngủi mà đạo đức quý hơn sống lâu mà buông lung](./song-ngan-ngui-ma-dao-duc-quy-hon-song-lau-ma-buong-lung.html)  
- [Kệ số 111: Mạng yểu mà trí tuệ quý hơn thọ mà si mê](./mang-yeu-ma-tri-tue-quy-hon-tho-ma-si-me.html)  
- [Kệ số 112: Sống ngắn ngủi mà tinh cần quý hơn sống lâu mà giải đãi](./song-ngan-ngui-ma-tinh-can-quy-hon-song-lau-ma-giai-dai.html)  
- [Kệ số 113: Ðời sống suy tư, dầu có ngắn ngủi, còn hơn sống lâu mà không suy gẫm](./doi-song-suy-tu.html)  
- [Kệ số 114: Sống một ngày mà chứng ngộ trạng thái bất diệt quý hơn sống cả thế kỷ mà không chứng](./mot-ngay-chung-ngo.html)  
- [Kệ số 115: Một ngày nhận thấy giáo pháp quý hơn cả thế kỷ không thấy](./mot-ngay-nhan-thay-giao-phap-quy-hon-ca-the-ky-khong-thay.html)  

[**Phẩm Điều Ác**](./pham-dieu-ac.html)

- [Kệ số 116: Hãy gấp rút làm việc thiện dập tắt điều ác](./hay-gap-rut-lam-viec-thien.html)  
- [Kệ số 117: Không nên lặp đi lặp lại điều ác](./khong-nen-lap-di-lap-lai-dieu-ac.html)  
- [Kệ số 118: Hãy lặp đi lặp lại điều thiện](./hay-lap-di-lap-lai-dieu-thien.html)  
- [Kệ số 119, 120: Quả trổ sẽ biết hành động ác hay thiện](./qua-tro-se-biet-hanh-dong-ac-hay-thien.html)  
- [Kệ số 121: Không nên xem thường điều ác](./khong-nen-xem-thuong-dieu-ac.html)  
- [Kệ số 122: Không nên xem thường điều thiện](./khong-nen-xem-thuong-dieu-thien.html)  
- [Kệ số 123: Hãy tránh điều ác như lánh xa một con đường nguy hiểm](./hay-lanh-xa-dieu-ac-nhu-lanh-xa-mot-con-duong-nguy-hiem.html)  
- [Kệ số 124: Người không có ý định xấu sẽ không tạo nghiệp ác](./nguoi-khong-co-y-dinh-xau-se-khong-tao-nghiep-ac.html)  
- [Kệ số 125: Ai gây tổn hại cho người vô tội sẽ chịu sầu muộn](./ai-gay-ton-hai-cho-nguoi-vo-toi-se-chiu-sau-muon.html)  
- [Kệ số 126: Tái sanh tùy thuộc nơi hành động](./tai-sanh-tuy-noi-hanh-dong.html)  
- [Kệ số 127: Không ai tránh được hậu quả của nghiệp ác đã tạo](./khong-ai-tranh-duoc-hau-qua-nghiep-ac-da-tao.html)  
- [Kệ số 128: Không thể khắc phục cái chết](./khong-the-khac-phuc-cai-chet.html)  

[**Phẩm Hình Phạt**](./pham-hinh-phat.html)

- [Kệ số 129: Không nên sát hại](./khong-nen-sat-hai.html)  
- [Kệ số 130: Tất cả đều quý trọng đời sống](./tat-ca-deu-quy-trong-doi-song.html)  
- [Kệ số 131, 132: Không nên hành hạ](./khong-nen-hanh-ha.html)  
- [Kệ số 133, 134: Không nói lời thô lỗ, hãy giữ im lặng](./khong-noi-loi-tho-lo.html)  
- [Kệ số 135: Không ai tránh được cảnh già, chết](./khong-ai-tranh-duoc-canh-gia-chet.html)  
- [Kệ số 136: Người hành ác bị quả dữ thiêu đốt](./nguoi-hanh-ac-bi-qua-du-thieu-dot.html)  
- [Kệ số 137 - 140: Kẻ xâm phạm người vô tội đi đến sầu muộn](./ke-xam-pham-nguoi-vo-toi-di-den-sau-muon.html)  
- [Kệ số 141: Lối sống ép xác không làm con người trở nên trong sạch](./loi-song-ep-xac-khong-lam-con-nguoi-tro-nen-trong-sach.html)  
- [Kệ số 142: Hình dáng bề ngoài không biến đổi người phàm ra thánh](./hinh-dang-be-ngoai-khong-bien-doi-nguoi-pham-ra-thanh.html)  
- [Kệ số 143, 144: Thế gian hiếm người khiêm tốn, hãy nghiêm trì giới đức, tiêu trừ đau khổ ](./the-gian-hiem-nguoi-khiem-ton.html)  
- [Kệ số 145: Người tốt tự kiểm soát](./nguoi-tot-tu-kiem-soat.html)  

[**Phẩm Sự Già**](./pham-su-gia.html)

- [Kệ số 146: Tìm ánh sáng](./tim-anh-sang.html)  
- [Kệ số 147: Thể xác lộng lẫy này quả thật ô trược](./the-xac-nay-qua-that-o-truoc.html)  
- [Kệ số 148: Ðời sống chấm dứt trong sự chết](./doi-song-cham-dut-trong-su-chet.html)  
- [Kệ số 149: Nhìn một đống xương thì có gì thích thú](./nhin-mot-dong-xuong-thi-co-gi-thich-thu.html)  
- [Kệ số 150: Thể xác này gồm thịt và máu](./the-xac-nay-gom-thit-va-mau.html)  
- [Kệ số 151: Đức hạnh chân chánh không hư cũ](./duc-hanh-chan-chinh-khong-hu-cu.html)  
- [Kệ số 152: Người học ít kém trí tuệ](./nguoi-hoc-it-kem-tri-tue.html)  
- [Kệ số 153, 154: Ái dục là người xây dựng cái nhà này](./ai-duc-la-nguoi-xay-dung-cai-nha-nay.html)  
- [Kệ số 155, 156: Người không tiến bộ sẽ ăn năn hối hận](./nguoi-khong-tien-bo-se-an-nan-hoi-han.html)  

[**Phẩm Tự Ngã**](./pham-tu-nga.html)

- [Kệ số 157: Hãy giác tỉnh](./hay-giac-tinh.html)  
- [Kệ số 158: Thầy phải làm gương trước](./thay-phai-lam-guong-truoc.html)  
- [Kệ số 159: Dạy người như thế nào, hành như thế ấy](./day-nguoi-the-nao-hanh-the-ay.html)  
- [Kệ số 160: Ta là nương tựa của ta](./ta-la-nuong-tua-cua-ta.html)  
- [Kệ số 161: Ta chịu trách nhiệm về hành động ác của ta](./ta-chiu-trach-nhiem-voi-hanh-dong-ac-cua-ta.html)  
- [Kệ số 162: Người ô nhiễm làm cho mình sụp đổ](./nguoi-o-nhiem-lam-minh-sup-do.html)  
- [Kệ số 163: Làm ác thì dễ, điều lành thật khó làm](./lam-ac-thi-de-dieu-lanh-that-kho-lam.html)  
- [Kệ số 164: Không nên khinh thường bậc cao quý](./khong-nen-khinh-nhuong-bac-cao-quy.html)  
- [Kệ số 165: Trong sạch hay ô nhiễm đều do nơi ta](./trong-sach-hay-o-nhiem-deu-do-noi-ta.html)  
- [Kệ số 166: Hãy chuyên cần để thành đạt an lạc tinh thần](./hay-chuyen-can-de-thanh-dat-an-lac-tinh-than.html)  

[**Phẩm Thế Gian**](./pham-the-gian.html)

- [Kệ số 167: Hãy từ bỏ tham vọng thấp hèn](./hay-tu-bo-tham-vong-thap-hen.html)  
- [Kệ số 168, 169: Người chánh hạnh sống an vui](./nguoi-chanh-hanh-song-an-vui.html)  
- [Kệ số 170: Thế gian này tựa hồ như bọt nước](./the-gian-nay-tua-ho-nhu-bot-nuoc.html)  
- [Kệ số 171: Người thiện trí không luyến ái thế gian](./nguoi-thien-tri-khong-luyen-ai-the-gian.html)  
- [Kệ số 172: Người chuyên cần chánh niệm rọi sáng thế gian](./nguoi-chuyen-can-chanh-niem-roi-sang-the-gian.html)  
- [Kệ số 173: Hành động lành có thể che lấp nghiệp xấu](./hanh-dong-lanh-co-the-che-lap-nghiep-xau.html)  
- [Kệ số 174: Người sáng suốt hiếm có](./nguoi-sang-suot-hiem-co.html)  
- [Kệ số 175: Người thiện trí cố thoát ra khỏi thế gian này](./nguoi-thien-tri-co-thoat-ra-khoi-the-gian-nay.html)  
- [Kệ số 176: Không có điều ác nào mà người gian dối không làm được](./khong-co-dieu-ac-nao-ma-nguoi-gian-doi-khong-lam-duoc.html)  
- [Kệ số 177: Người bỏn xẻn không hạnh phúc](./nguoi-bon-xen-khong-hanh-phuc.html)  
- [Kệ số 178: Tiến bộ tinh thần quý hơn quyền bá chủ trên thế gian](./tien-bo-tinh-than-quy-hon-quyen-ba-chu-tren-the-gian.html)  

[**Phẩm Đức Phật**](./pham-duc-phat.html)

- [Kệ số 179, 180: Ðức Phật vô lượng](./duc-phat-vo-luong.html)  
- [Kệ số 181: Ðức Phật được tất cả kính mộ](./duc-phat-duoc-tat-ca-kinh-mo.html)  
- [Kệ số 182: Hiếm có một vị Phật](./hiem-co-mot-vi-phat.html)  
- [Kệ số 183 - 185: Hãy tạo thiện nghiệp, sống đời trong sạch](./hay-tao-thien-nghiep-song-doi-trong-sach.html)  
- [Kệ số 186, 187: Khoái lạc vật chất không bao giờ thỏa mãn](./khoai-lac-vat-chat-khong-bao-gio-thoa-man.html)  
- [Kệ số 188 - 192: Hãy tìm quy y Phật, pháp, tăng, để thoát khổ](./quy-y-de-thoat-kho.html)  
- [Kệ số 193: Hạng người cao quý thật hi hữu](./hang-nguoi-cao-quy-that-hi-huu.html)  
- [Kệ số 194: Những điều đem lại hạnh phúc](./nhung-dieu-dem-lai-hanh-phuc.html)  
- [Kệ số 195, 196: Tôn kính bậc đáng tôn kính](./ton-kinh-bac-dang-kinh.html)  

[**Phẩm An Lạc**](./pham-an-lac.html)

- [Kệ số 197 - 199: Không hận thù giữa người thù hận](./khong-han-thu-giua-nguoi-thu-han.html)  
- [Kệ số 200: Hãy tiêu trừ chướng ngại](./hay-tieu-tru-chuong-ngai.html)  
- [Kệ số 201: Chiến thắng nuôi dưỡng hận thù](./chien-thang-nuoi-duong-han-thu.html)  
- [Kệ số 202: Tham ái là lửa](./tham-ai-la-lua.html)  
- [Kệ số 203: Bụng đói là phiền não quan trọng](./bung-doi-la-phien-nao-quan-trong.html)  
- [Kệ số 204: Sức khỏe là vàng](./suc-khoe-la-vang.html)  
- [Kệ số 205: Hạnh phúc thay người nếm hương vị của chân lý](./hanh-phuc-thay-nguoi-nem-huong-vi-cua-chan-ly.html)  
- [Kệ số 206 - 208: Phước báu thay được diện kiến bậc thánh nhân](./phuoc-bau-thay-duoc-dien-kien-bac-thanh-nhan.html)  

[**Phẩm Hỷ Ái**](./pham-hy-ai.html)

- [Kệ số 209 - 211: Hãy tránh những gì phải tránh](./hay-tranh-nhung-gi-phai-tranh.html)  
- [Kệ số 212: Thân yêu sanh sầu muộn](./than-yeu-sanh-sau-muon.html)  
- [Kệ số 213: Mến thương sanh sầu muộn](./men-thuong-sanh-sau-muon.html)  
- [Kệ số 214: Luyến ái sanh sầu muộn](./luyen-ai-sanh-sau-muon.html)  
- [Kệ số 215: Tham dục sanh sầu muộn](./tham-duc-sanh-sau-muon.html)  
- [Kệ số 216: Tham ái sanh sầu muộn](./tham-ai-sanh-sau-muon.html)  
- [Kệ số 217: Người giới hạnh được tất cả kính mộ](./nguoi-gioi-hanh-duoc-tat-ca-kinh-mo.html)  
- [Kệ số 218: Người không luyến ái, ở phía trên dòng suối](./nguoi-khong-luyen-ai-o-phia-tren-dong-suoi.html)  
- [Kệ số 219, 220: Phước báu đón rước người hành thiện](./phuoc-bau-don-ruoc-nguoi-hanh-thien.html)  

[**Phẩm Phẫn Nộ**](./pham-phan-no.html)

- [Kệ số 221: Hãy dứt bỏ sân hận](./hay-dut-bo-san-han.html)  
- [Kệ số 222: Hãy chế ngự tâm sân](./hay-che-ngu-tam-san.html)  
- [Kệ số 223: Hãy lấy tình thương chế ngự tâm sân](./hay-lay-tinh-thuong-che-ngu-tam-san.html)  
- [Kệ số 224: Hãy chân chật, nhẫn nại, và bố thí](./hay-chan-that-nhan-nai-va-bo-thi.html)  
- [Kệ số 225: Bậc vô hại thành đạt trạng thái bất diệt](./bac-vo-hai-thanh-dat-trang-thai-bat-diet.html)  
- [Kệ số 226: Người giác tỉnh xa lìa các hoặc lậu](./nguoi-giac-tinh-xa-lia-cac-hoac-lau.html)  
- [Kệ số 227 - 230: Khiển trách](./khien-trach.html)  
- [Kệ số 231 - 234: Hãy giữ thân, khẩu, ý, trong sạch](./hay-giu-than-khau-y-trong-sach.html)  

[**Phẩm Cấu Uế**](./pham-cau-ue.html)

- [Kệ số 235 - 238: Cái chết đã gần kề, hãy tinh tấn chuyên cần](./cai-chet-gan-ke.html)  
- [Kệ số 239: Hãy tự thanh lọc dần dần](./hay-tu-thanh-loc-dan-dan.html)  
- [Kệ số 240: Hành động ác làm suy sụp người hành ác](./hanh-dong-ac-lam-suy-sup-nguoi-hanh-ac.html)  
- [Kệ số 241: Nguyên nhân của uế trược](./nguyen-nhan-cua-ue-truoc.html)  
- [Kệ số 242, 243: Uế trược là điều ác, vô minh là uế trước lớn nhất](./vo-minh-la-ue-truoc-lon-nhat.html)  
- [Kệ số 244, 245: Sống không biết hổ thẹn là dễ, sống đời khiêm tốn là khó](./song-khong-biet-ho-then-la-de.html)  
- [Kệ số 246 - 248: Người không giữ ngũ giới tự làm mình sụp đổ](./nguoi-khong-giu-ngu-gioi-tu-lam-minh-sup-do.html)  
- [Kệ số 249, 250: Người có tâm đố kỵ không an tịnh](./nguoi-co-tam-do-ky-khong-an-tinh.html)  
- [Kệ số 251: Không có sông nào như ái dục](./khong-co-song-nao-nhu-ai-duc.html)  
- [Kệ số 252: Thấy lỗi của người thì dễ](./thay-loi-nguoi-thi-de.html)  
- [Kệ số 253: Bên trong những người chỉ tìm lỗi của kẻ khác, ô nhiễm sanh thêm ô nhiễm](./ben-trong-ke-chi-tim-loi-nguoi-khac-o-nhiem-sanh-them-o-nhiem.html)  
- [Kệ số 254, 255: Bên ngoài không có bậc thánh](./ben-ngoai-khong-co-bac-thanh.html)  

[**Phẩm Chánh Hạnh**](./pham-chanh-hanh.html)

- [Kệ số 256, 257: Công bằng không thiên vị](./cong-bang-khong-thien-vi.html)  
- [Kệ số 258: Không phải nói nhiều là có trí tuệ](./khong-phai-noi-nhieu-la-co-tri-tue.html)  
- [Kệ số 259: Người thông suốt giáo pháp không ham nói](./nguoi-thong-suot-giao-phap-khong-ham-noi.html)  
- [Kệ số 260, 261: Không phải tóc bạc là Đại Đức](./khong-phai-toc-bac-la-dai-duc.html)  
- [Kệ số 262, 263: Hình dáng bề ngoài không làm con người trở nên lương thiện](./be-ngoai-khong-lam-con-nguoi-tro-nen-luong-thien.html)  
- [Kệ số 264, 265: Ðầu tròn vai vuông không tạo nên thầy Tỳ-kheo](./dau-tron-vai-vuong-khong-tao-nen-thay-ty-kheo.html)  
- [Kệ số 266, 267: Không phải chỉ đi khất thực là thành Tỳ-kheo](./khong-phai-chi-khat-thuc-la-thanh-ty-kheo.html)  
- [Kệ số 268, 269: Im lặng không làm nên bậc hiền thánh](./im-lang-khong-lam-nen-bac-hien-thanh.html)  
- [Kệ số 270: Do bản tính không gây tổn hại con người trở thành bậc thánh](./khong-gay-ton-hai.html)  
- [Kệ số 271, 272: Đừng mãn nguyện khi chưa tận diệt hết dục vọng](./dung-man-nguyen-khi-chua-tan-diet-het-duc-vong.html)  

[**Phẩm Đạo Lộ**](./pham-dao-lo.html)

- [Kệ số 273 - 276: Bát chánh đạo là con đường cao thượng nhất](./bat-chanh-dao-la-con-duong-cao-thuong-nhat.html)  
- [Kệ số 277: Tất cả các vật hữu lậu đều vô thường](./tat-ca-cac-vat-huu-lau-deu-vo-thuong.html)  
- [Kệ số 278: Tất cả các vật hữu lậu đều khổ snão](./tat-ca-cac-vat-huu-lau-deu-kho-nao.html)  
- [Kệ số 279: Tất cả đều vô ngã](./tat-ca-deu-vo-nga.html)  
- [Kệ số 280: Kẻ lười biếng không chứng ngộ con đường](./ke-luoi-bieng-khong-chung-ngo-con-duong.html)  
- [Kệ số 281: Hãy thanh lọc thân, khẩu, ý](./hay-thanh-loc-than-khau-y.html)  
- [Kệ số 282: Hãy làm thế nào để tăng trưởng trí tuệ](./hay-lam-the-nao-de-tang-truong-tri-tue.html)  
- [Kệ số 283, 284: Hãy dứt bỏ luyến ái ngày nào còn luyến ái, tâm còn bị trói buộc](./hay-dut-bo-luyen-ai.html)  
- [Kệ số 285: Hãy phát triển con đường an tịnh](./hay-phat-trien-con-duong-an-tinh.html)  
- [Kệ số 286: Kẻ si mê không nhận định mối hiểm họa của sự chết](./ke-si-me-khong-nhan-dinh-moi-hiem-hoa-cua-su-chet.html)  
- [Kệ số 287: Cái chết nắm lấy kẻ đam mê](./cai-chet-nam-lay-ke-dam-me.html)  
- [Kệ số 288, 289: Trong giờ phút lâm chung không có sự bảo trợ của ai cả](./gio-phut-lam-chung-khong-co-bao-tro.html)  

[**Phẩm Tạp Lục**](./pham-tap-luc.html)

- [Kệ số 290: Hãy từ bỏ hạnh phúc nhỏ để thành đạt hạnh phúc to](./tu-bo-hanh-phuc-nho-de-dat-hanh-phuc-to.html)  
- [Kệ số 291: Không lấy thù đáp lại thù](./khong-lay-thu-dap-lai-thu.html)  
- [Kệ số 292, 293: Hoặc lậu của người ngã mạn tăng trưởng](./hoac-lau-cua-nguoi-nga-man-tang-truong.html)  
- [Kệ số 294, 295: A-La-Hán không sầu muộn](./a-la-han-khong-sau-muon.html)  
- [Kệ số 296 - 301: Suy niệm về Tam Bảo](./suy-niem-ve-tam-bao.html)  
- [Kệ số 302: Dứt bỏ là khó](./dut-bo-la-kho.html)  
- [Kệ số 303: Người có tâm đạo ở đâu cũng được quý trọng](./nguoi-co-tam-dao-o-dau-cung-duoc-quy-trong.html)  
- [Kệ số 304: Người tốt được nhận thấy từ xa](./nguoi-tot-duoc-nhan-thay-tu-xa.html)  
- [Kệ số 305: Thỏa thích trong cảnh cô đơn tịch mịch](./thoa-thich-trong-canh-co-don-tich-mich.html)  

[**Phẩm Địa Ngục**](./pham-dia-nguc.html)

- [Kệ số 306: Kẻ nói dối chịu đau khổ](./ke-noi-doi-chiu-dau-kho.html)  
- [Kệ số 307: Tỳ-kheo ô nhiễm chịu đau khổ](./ty-kheo-o-nhiem-chiu-canh-kho.html)  
- [Kệ số 308: Không nên làm người bất thiện](./khong-nen-lam-nguoi-bat-thien.html)  
- [Kệ số 309, 310: Tà dâm là tạo nghiệp ác](./ta-dam-la-tao-nghiep-ac.html)  
- [Kệ số 311 - 313: Kiếp sống ô nhiễm kết thúc trong đau khổ](./kiep-song-o-nhiem-ket-thuc-trong-dau-kho.html)  
- [Kệ số 314: Dầu một lỗi nhỏ cũng không nên phạm](./dau-mot-loi-nho-cung-khong-nen-pham.html)  
- [Kệ số 315: Hãy cẩn mật giữ mình như canh phòng một thành trì](./hay-can-mat-giu-minh-nhu-canh-phong-mot-thanh-tri.html)  
- [Kệ số 316, 317: Không nên sợ điều không đáng sợ](./khong-nen-so-dieu-khong-dang-so.html)  
- [Kệ số 318, 319: Thấy sai biết sai thấy đúng biết đúng](./thay-sai-biet-sai-thay-dung-biet-dung.html)  

[**Phẩm Con Voi**](./pham-con-voi.html)

- [Kệ số 320 - 322: Hạnh phúc thay, người tự chế ngự](./hanh-phuc-thay-nguoi-tu-che-ngu.html)  
- [Kệ số 323: Tự kiểm soát đưa đến mục tiêu](./tu-kiem-soat-dua-den-muc-tieu.html)  
- [Kệ số 324: Voi con biết lo cho mẹ](./voi-con-biet-lo-cho-me.html)  
- [Kệ số 325: Ẩm thực tiết độ](./am-thuc-tiet-do.html)  
- [Kệ số 326: Hãy kiểm soát tư tưởng](./hay-kiem-soat-tu-tuong.html)  
- [Kệ số 327: Hãy lánh xa đường ác](./hay-lanh-xa-duong-ac.html)  
- [Kệ số 328 - 330: Hãy kết hợp với bậc thiện trí](./hay-ket-hop-voi-bac-thien-tri.html)  
- [Kệ số 331 - 333: Hạnh phúc thay](./hanh-phuc-thay.html)  

[**Phẩm Ái Dục**](./pham-ai-duc.html)

- [Kệ số 334 - 337: Ái dục phát sanh đến người sống dể duôi](./ai-duc-phat-sanh-den-nguoi-song-de-duoi.html)  
- [Kệ số 338 - 343: Bao giờ còn ái dục là còn đau khổ](./bao-gio-con-ai-duc-la-con-dau-kho.html)  
- [Kệ số 344: Trở về đời sống thế gian là điên cuồng](./tro-ve-doi-song-the-gian-la-dien-cuong.html)  
- [Kệ số 345, 346: Dây trói buộc của ngũ trần còn ngàn lần bền chắc hơn dây xích](./day-troi-buoc-cua-ngu-tran-con-ngan-lan-ben-chac-hon-day-xich.html)  
- [Kệ số 347: Kẻ tham ái bị mắc trong lưới tham của mình](./ke-tham-ai-bi-mac-trong-luoi-tham-cua-minh.html)  
- [Kệ số 348: Hãy thoát ly cái tâm](./hay-thoat-ly-cai-tam.html)  
- [Kệ số 349, 350: Tâm niệm chấm dứt ái dục](./tam-niem-cham-dut-ai-duc.html)  
- [Kệ số 351, 352: Người thoát ly ái dục sống kiếp sống cuối cùng](./nguoi-thoat-ly-ai-duc-song-kiep-song-cuoi-cung.html)  
- [Kệ số 353: Ðấng toàn giác không có thầy](./dang-toan-giac-khong-co-thay.html)  
- [Kệ số 354: Bố thí chân lý cao thượng hơn tất cả](./bo-thi-chan-ly-cao-thuong-hon-tat-ca.html)  
- [Kệ số 355: Sự giàu sang làm sụp đổ kẻ si mê](./su-giau-sang-lam-sup-do-ke-si-me.html)  
- [Kệ số 356 - 359: Khuyết điểm của loài người](./khuyet-diem-cua-loai-nguoi.html)  

[**Phẩm Tỳ-Kheo**](./pham-ty-kheo.html)

- [Kệ số 360, 361: Hãy thu thúc lục căn](./hay-thu-thuc-luc-can.html)  
- [Kệ số 362: Người tự kiềm chế hoàn toàn được gọi là Tỳ-kheo](./nguoi-tu-kiem-che-hoan-toan-duoc-goi-la-ty-kheo.html)  
- [Kệ số 363: Người điều phục lưỡi có lời nói êm dịu](./nguoi-dieu-phuc-luoi-co-loi-em-diu.html)  
- [Kệ số 364: Người thỏa thích trong giáo pháp không rơi trở xuống](./nguoi-thoa-thich-trong-giao-phap-khong-roi-xuong.html)  
- [Kệ số 365, 366: Hãy tri túc](./hay-tri-tuc.html)  
- [Kệ số 367: Vị ấy là Tỳ-kheo vì không còn luyến ái](./vi-ay-la-ty-kheo-vi-khong-con-luyen-ai.html)  
- [Kệ số 368 - 376: Để xứng làm tỳ-kheo](./de-xung-lam-ty-kheo.html)  
- [Kệ số 377: Hãy vất bỏ tham sân](./hay-vat-bo-tham-san.html)  
- [Kệ số 378: Người thoát ly thế tình sống an tịnh](./nguoi-thoat-ly-the-tinh-song-an-tinh.html)  
- [Kệ số 379, 380: Người tự điều chế sống an lành hạnh phúc](./nguoi-tu-dieu-che-song-an-lanh-hanh-phuc.html)  
- [Kệ số 381: Với phỉ lạc và niềm tin, hãy cố gắng thành đạt mục tiêu](./voi-phi-lac-va-niem-tin-hay-co-gang-thanh-dat-muc-tieu.html)  
- [Kệ số 382: Lòng nhiệt thành với giáo pháp rọi sáng thế gian](./long-nhiet-thanh-voi-giao-phap-roi-sang-the-gian.html)  

[**Phẩm Bà-La-Môn**](./pham-ba-la-mon.html)

- [Kệ số 383: Hãy làm người thấu suốt trạng thái vô tạo](./hay-lam-nguoi-sang-suot-trang-thai-vo-tao.html)  
- [Kệ số 384: Hãy trau giồi tâm định và tuệ minh sát](./hay-trau-doi-tam-dinh-va-tue-minh-sat.html)  
- [Kệ số 385: Bà-La-Môn là người không bị ràng buộc](./ba-la-mon-la-nguoi-khong-bi-rang-buoc.html)  
- [Kệ số 386: Bà-La-Môn là người hành thiền và trong sạch](./ba-la-mon-la-nguoi-hanh-thien-va-trong-sach.html)  
- [Kệ số 387: Ðức Phật rạng tỏ, ngày như đêm](./duc-phat-rang-to-ngay-nhu-dem.html)  
- [Kệ số 388: Là thánh nhân vì đã xa lìa ác nghiệp](./la-thanh-nhan-vi-da-xa-lia-ac-nghiep.html)  
- [Kệ số 389, 390: Chớ gây tổn hại một vị A-la-hán](./cho-gay-ton-hai-mot-vi-a-la-han.html)  
- [Kệ số 391: Thực sự Bà-la-môn là người thận trọng thu thúc](./that-su-ba-la-mon-la-nguoi-than-trong-thu-thuc.html)  
- [Kệ số 392: Hãy tôn kính những bậc đáng kính](./hay-ton-kinh-nhung-bac-dang-kinh.html)  
- [Kệ số 393: Trong sạch thay, người chân thật và chánh hạnh](./trong-sach-thay-nguoi-chan-that-va-chanh-hanh.html)  
- [Kệ số 394: Hãy thanh tịnh bên trong](./hay-thanh-tinh-ben-trong.html)  
- [Kệ số 395: Bà-La-Môn là người hành thiền trong rừng một mình](./ba-la-mon-la-nguoi-hanh-thien-trong-rung-mot-minh.html)  
- [Kệ số 396: Bà-La-Môn là người không tài sản và không luyến ái](./ba-la-mon-la-nguoi-khong-tai-san-va-luyen-ai.html)  
- [Kệ số 397: Bà-La-Môn là người tận diệt mọi thằng thúc](./ba-la-mon-la-nguoi-tan-diet-moi-thang-thuc.html)  
- [Kệ số 398: Bà-La-Môn là người không sân hận](./ba-la-mon-la-nguoi-khong-san-han.html)  
- [Kệ số 399: Bà-La-Môn là người nhẫn nại](./ba-la-mon-la-nguoi-nhan-nai.html)  
- [Kệ số 400: Bà-La-Môn là người không nóng giận](./ba-la-mon-la-nguoi-khong-nong-gian.html)  
- [Kệ số 401: Bà-La-Môn không luyến ái dục lạc](./ba-la-mon-khong-luyen-ai-duc-lac.html)  
- [Kệ số 402: Bà-La-Môn là người đã bỏ gánh nặng xuống](./ba-la-mon-la-nguoi-da-bo-ganh-nang-xuong.html)  
- [Kệ số 403: Bà-La-Môn là người đã đạt mục tiêu cùng tột](./ba-la-mon-la-nguoi-da-dat-duoc-muc-tieu-cung-tot.html)  
- [Kệ số 404: Bà-La-Môn là người không trìu mến](./ba-la-mon-la-nguoi-khong-triu-men.html)  
- [Kệ số 405: Bà-La-Môn là người không gây tổn thương cho bất kỳ ai](./ba-la-mon-la-nguoi-khong-gay-ton-thuong-cho-bat-ky-ai.html)  
- [Kệ số 406: Bà-La-Môn là người thân hữu giữa đám đông thù nghịch](./ba-la-mon-la-nguoi-than-huu-giua-dam-dong-thu-dich.html)  
- [Kệ số 407: Bà-La-Môn là người lánh xa mọi khát vọng](./ba-la-mon-la-nguoi-lanh-xa-moi-khat-vong.html)  
- [Kệ số 408: Bà-La-Môn là người không xúc phạm đến ai](./ba-la-mon-la-nguoi-khong-xuc-pham-den-ai.html)  
- [Kệ số 409: Bà-La-Môn là người không trộm cắp](./ba-la-mon-la-nguoi-khong-trom-cap.html)  
- [Kệ số 410: Bà-La-Môn là người không tham vọng](./ba-la-mon-la-nguoi-khong-tham-vong.html)  
- [Kệ số 411: Bà-La-Môn là người không còn luyến ái](./ba-la-mon-la-nguoi-khong-con-luyen-ai.html)  
- [Kệ số 412: Bà-La-Môn là người đã vượt khỏi thiện và ác](./ba-la-mon-la-nguoi-da-vuot-khoi-thien-ac.html)  
- [Kệ số 413: Bà-La-Môn là người trong sạch](./ba-la-mon-la-nguoi-trong-sach.html)  
- [Kệ số 414: Bà-La-Môn là người không bám bíu vào điều chi](./ba-la-mon-la-nguoi-khong-bam-viu-vao-dieu-chi.html)  
- [Kệ số 415: Bà-La-Môn là người đã dứt bỏ dục lạc](./ba-la-mon-la-nguoi-da-dut-bo-duc-lac.html)  
- [Kệ số 416: Bà-La-Môn là người dứt bỏ ái dục](./ba-la-mon-la-nguoi-dut-bo-ai-duc.html)  
- [Kệ số 417: Bà-La-Môn là người đã tách rời mọi ràng buộc](./ba-la-mon-la-nguoi-da-tach-roi-moi-rang-buoc.html)  
- [Kệ số 418: Bà-La-Môn là người đã dứt bỏ ưa và ghét](./ba-la-mon-la-nguoi-da-dut-bo-ua-va-ghet.html)  
- [Kệ số 419, 420: Bà-La-Môn là người đã đắc quả A-La-Hán](./ba-la-mon-la-nguoi-da-dac-qua-a-la-han.html)  
- [Kệ số 421: Bà-La-Môn là người không ao ước gì](./ba-la-mon-la-nguoi-khong-uoc-ao-gi.html)  
- [Kệ số 422: Bà-La-Môn là người đã giác ngộ](./ba-la-mon-la-nguoi-da-giac-ngo.html)  
- [Kệ số 423: Bà-La-Môn là người tự làm cho mình trở nên toàn thiện](./ba-la-mon-la-nguoi-tu-lam-cho-minh-tro-nen-toan-thien.html)  
